### ISSUE TITLE
Set up the repo infrastructure

### ISSUE THREAD

**Issue by mengqiy** [kubernetes-sigs/krm-functions-registry#3]
In phase 1, we want to focus on container as fn runtime.

- [x] Write the 1st in-tree function (render-helm-chart)
- [x] Set up infrastructure for the fn registry repo
- [x] CI for in-tree functions: Prow, GitHub Action
- [ ] release pipeline for in-tree functions: GitHub Action
- [x] CI for all functions. E.g. verify metadata
- [ ] Templates for different kinds of publishers.
- [ ] Support workflows (user guide doc + CI):
  - [ ] A contributor contribute a new out-of-tree function
  - [ ] A publisher can snapshot its functions and publish them in a catalog.
- Website:
  - [ ] Support browsing usage doc and examples
  - [ ] Serve static snapshotted catalog and dynamic aggregation catalog by publisher

In phase 2, we want to support exec as fn runtime.

**Comment by natasha41575** [comment]
@mengqiy Did you have any specific way you wanted the release pipeline to work? In kustomize we use a GCP project to generate release artifacts and publish docker images. We may be able to do the same thing for this repo, I will investigate.

**Comment by natasha41575** [comment]
e2e testing: https://github.com/kubernetes-sigs/krm-functions-registry/pull/5
prow test: https://github.com/kubernetes/test-infra/pull/25013
setting up our GCP project to stage our images: https://github.com/kubernetes/k8s.io/pull/3390

**Comment by mengqiy** [comment]
It seems Prow only supports periodics, presubmits and postsubmits. I guess it won't be very useful for releasing KRM functions.
Using Cloud Build seems to be OK if we use a project owned by CNCF. What GCP project are we using for kustomize?

**Comment by natasha41575** [comment]
Kustomize has the project k8s-staging-kustomize, configured here: https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io/images/k8s-staging-kustomize. 

I think you don't have access to the kustomize GCP project, but it is here: https://console.cloud.google.com/home/dashboard?project=k8s-staging-kustomize

I am trying to do the same thing for the krm functions with this PR https://github.com/kubernetes/k8s.io/pull/3390, following the instructions [here](https://github.com/kubernetes/k8s.io/tree/main/k8s.gcr.io#Creating-staging-repos)
